import classNames from 'classnames';
import Wrapper from '../components/Wrapper';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.className,
          'dark:bg-slate-800 bg-white min-h-screen'
        )}
      >
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
